{
 "title": "Kafka Simple Monitor",
 "tags": [ "kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Controller",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_activecontrollercount"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_offlinepartitionscount"
    }
   ]
  },
  {
   "title": "Under-Replicated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount"
    }
   ]
  },
  {
   "title": "Messages In Rate (All Topics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Rate (Consumer Activity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Your Topics - Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"transactions_raw\"}[1m])",
     "legendFormat": "transactions_raw"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"currency_rates\"}[1m])",
     "legendFormat": "currency_rates"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"users_profile\"}[1m])",
     "legendFormat": "users_profile"
    }
   ]
  },
  {
   "title": "All Topics - Total Message Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total"
    }
   ]
  }
 ]
}